service: aws-python # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

custom:
  secrets: ${file(secrets.yml)}

functions:
  webhook:
    handler: handler.hello
    events:
      - http:
          path: posts/webhook
          method: post
    environment:
      SECRET_KEY: ${self:custom.secrets.SECRET_KEY}
